<a href="https://colab.research.google.com/github/mmohammadi4820/Book_ArtificialIntelligence/blob/main/MLDL_Lab01_Ex01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
x = torch.rand((7,7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
y = torch.randn((1,7))
y_t= y.view(7,1)
# Perform matrix multiplication
mult_matrix = torch.matmul(x,y_t)

In [ ]:
print(mult_matrix)
mult_matrix.size()

tensor([[ 0.1118],
        [ 0.2037],
        [ 0.3746],
        [-0.6796],
        [ 0.6498],
        [-0.6427],
        [-0.7328]])


torch.Size([7, 1])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed

torch.manual_seed(0)

# Create two random tensors

x2=torch.randn((7,7))
y2=torch.randn((7,7))

# Matrix multiply tensors

mult_matrix2 = torch.matmul(x2,y2)
print(mult_matrix2)

tensor([[-3.4462, -0.6237, -1.4731, -0.1826, -2.9228, -0.7206,  1.4306],
        [-2.7913, -2.6098, -2.2022,  5.4936, -5.2200,  2.0827,  0.4208],
        [-2.2178,  0.6962,  1.0041, -4.6598,  5.8242, -0.2538,  4.6235],
        [ 0.6463, -0.7215, -0.6137,  3.7213, -3.8655,  1.9931, -2.1913],
        [ 4.5598,  1.0941,  1.6732, -3.7148,  5.1490,  4.3507,  3.1405],
        [ 0.3414,  0.5411,  0.4656,  2.7137,  1.1051,  0.5672,  0.5802],
        [ 2.2916, -1.4248, -0.4659, -9.4970, -1.3402, -0.6716, -0.0632]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)



:
### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

# Check if CUDA is available (CUDA is the software layer that allows GPU use)
if torch.cuda.is_available():
    print('CUDA is available. GPU is ready for use.')
    print('GPU Name:', torch.cuda.get_device_name(0))  # Print the name of the GPU
else:
    print('CUDA is not available. Running on CPU.')


CUDA is not available. Running on CPU.


In [ ]:
# Set the device to GPU if available, else CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Set the manual seed for reproducibility
torch.manual_seed(1234)

# Create two random tensors of shape (2, 3)
tensor1 = torch.rand((2, 3))
tensor2 = torch.rand((2, 3))

# Send both tensors to the GPU
tensor1_gpu = tensor1.to(device)
tensor2_gpu = tensor2.to(device)

# Output the tensors on the GPU
print(tensor1_gpu)
print(tensor2_gpu)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [ ]:

# Set the device to GPU if available, else CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Set random seed for reproducibility
# torch.manual_seed(42) # Uncomment if you need to set a seed for CPU and CUDA

# Create a random tensor and move it to the chosen device
x3 = torch.rand((2, 3)).to(device)
print(x3)

# Check for access to GPU
if torch.cuda.is_available():
    print("GPU is available.")
    # Create two random tensors on GPU
    a = torch.rand((2, 3), device=device)
    b = torch.rand((2, 3), device=device)
    print("First tensor on GPU:", a)
    print("Second tensor on GPU:", b)
else:
    print("GPU is not available, running on CPU.")


tensor([[0.9665, 0.7399, 0.4517],
        [0.4757, 0.7842, 0.1525]])
GPU is not available, running on CPU.


In [ ]:
# Set random seed
x3 = torch.rand((2,3))
print(x3.to('cuda'))

# Check for access to GPU

# Create two random tensors on GPU


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
